## Tensorflow 2版本

![title](./img/2.png)

### 既然出了2版本跟1.x相比有哪些优势呢？

- 首先Tensorflow是深度学习框架，定位就是工具，帮助我们完成实验和任务的，所以工具当然是使用起来越简单才是越实用的！

- 2版本并不是难度增大，而是大大简化是建模的方法和步骤，与1.X版本相比更简单实用了，难度更小了！

- 终于把Keras Api当做核心了，使用起来一句话概述就是简单它妈给简单开门。。。

- 跨平台，各种现成模型，eager mode使得调试起来终于不那么难受了！

- 先吹这么多吧！整体感觉就是用起来更接地气了，深度学习入门和进阶最好的方法就是多练习多试验，看论文复现代码和调试的过程我觉得是提升最快的途径！

![title](./img/1.png)

## Tensorflow 2版本安装

#### 1.安装Anaconda：https://www.anaconda.com/
- 这个是Python全家桶，必备！选择跟自己环境配套的最新版本就可以
- 网速慢的点这里：https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/

#### 2.安装Tensorflow: https://tensorflow.google.cn/
- CPU版本安装：pip install tensorflow
- GPU版本安装：pip install tensorflow-gpu 需要配置好CUDA10版本
- 如果安装报错了，那就自己下载一份：https://pypi.org/project/tensorflow-gpu/#files

### 先简单试试

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.4.1'

Oh My God，能直接得出结果！！！

In [3]:
# Eager Execution
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1,9],[3,6]])
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [3, 6]], dtype=int32)>

In [5]:
x = tf.add(x, 1)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2, 10],
       [ 4,  7]], dtype=int32)>

### Tensor是什么

- 当做是可以进行GPU加速计算的矩阵就可以

![Scalar, vector, matrix, tensor - a drawing by Tai-Danae Bradley](https://uploads-ssl.webflow.com/5b1d427ae0c922e912eda447/5cd99a73f8ce4494ad86852e_arraychart.jpg)

转换格式

In [6]:
x.numpy()

array([[ 2, 10],
       [ 4,  7]], dtype=int32)

In [7]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2., 10.],
       [ 4.,  7.]], dtype=float32)>

In [8]:
x1 = np.ones([2,2])
x2 = tf.multiply(x1, 2)
x2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2., 2.],
       [2., 2.]])>